# Generated by Django 6.0.3 on 2026-04-01 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_owner', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet')),
                ('veterinarian', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'vet'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_as_vet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
    ]
